//GLOBAL ACTION
export const SET_SCREEN_SIZE = "SET_SCREEN_SIZE";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_PROFILE_CONTENT = "SET_PROFILE_CONTENT";
export const IS_MESSAGE = "IS_MESSAGE";
export const MESSAGE = "MESSAGE";
export const IS_EDIT_MODAL = "IS_EDIT_MODAL";
export const IS_ALERT = "IS_ALERT";
export const SET_IS_NO_DATA = "SET_IS_NO_DATA";
export const GET_AIRLINES = "GET_AIRLINES";

//USER
export const SET_IS_LOGIN = "SET_IS_LOGIN";
export const SET_PROFILE_MENU = "SET_PROFILE_MENU";

//HOTEL
export const SET_IS_ADD_HOTEL = "SET_IS_ADD_HOTEL";
export const GET_ALL_DATA_HOTEL = "GET_ALL_DATA_HOTEL";
export const ADD_HOTEL = "ADD_HOTEL";
export const DELETE_HOTEL = "DELETE_HOTEL";
export const UPDATE_HOTEL = "UPDATE_HOTEL";

//PRODUCT
export const SET_NO_DATA_PRODUCT = "SET_NO_DATA_PRODUCT";
export const SET_IS_LOADING_PRODUCT = "SET_IS_LOADING_PRODUCT";
export const GET_DATA_PRODUCT = "GET_DATA_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_DATA_EDIT_PRODUCT = "SET_DATA_EDIT_PRODUCT";

//SCHEDULE
export const IS_SCHEDULE_FORM = "IS_SCHEDULE_FORM";
