//GLOBAL ACTION
export const SET_SCREEN_SIZE = 'SET_SCREEN_SIZE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_PROFILE_CONTENT = 'SET_PROFILE_CONTENT';

//USER
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const SET_PROFILE_MENU = 'SET_PROFILE_MENU';

//HOTEL
export const SET_IS_ADD_HOTEL = 'SET_IS_ADD_HOTEL';

//PRODUCT
export const SET_NO_DATA_PRODUCT = 'SET_NO_DATA_PRODUCT';
export const SET_IS_LOADING_PRODUCT = 'SET_IS_LOADING_PRODUCT';
export const GET_DATA_PRODUCT = 'GET_DATA_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'


